---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: starboard-cli
  namespace: dev
  labels:
    app.kubernetes.io/name: starboard-cli
    app.kubernetes.io/instance: starboard-cli
    app.kubernetes.io/version: "0.14.1"
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: starboard-cli
  labels:
    app.kubernetes.io/name: starboard-cli
    app.kubernetes.io/instance: starboard-cli
    app.kubernetes.io/version: "0.14.1"
    app.kubernetes.io/managed-by: kubectl
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - serviceaccounts
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
      - pods
    verbs:
      - list
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - list
      - get
  - apiGroups:
      - aquasecurity.github.io
    resources:
      - vulnerabilityreports
      - configauditreports
      - clusterconfigauditreports
      - ciskubebenchreports
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: starboard-cli
  labels:
    app.kubernetes.io/name: starboard-cli
    app.kubernetes.io/instance: starboard-cli
    app.kubernetes.io/version: "0.14.1"
    app.kubernetes.io/managed-by: kubectl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: starboard-cli
subjects:
  - kind: ServiceAccount
    name: starboard-cli
    namespace: dev
